//
//  TaskDetailView.swift
//  Cogito
//
//  Created by Prince Yadav on 24/11/24.
//

import SwiftUI

struct TaskDetailView: View {
    @Environment(\.dismiss) private var dismiss
    @ObservedObject var viewModel: TaskViewModel
    let task: Task
    
    @State private var editedTitle: String
    @State private var editedDescription: String
    @State private var editedDueDate: Date
    @State private var editedPriority: Task.TaskPriority
    @State private var editedCategories: [String]
    @State private var newCategory: String = ""
    
    init(viewModel: TaskViewModel, task: Task) {
        self.viewModel = viewModel
        self.task = task
        _editedTitle = State(initialValue: task.title)
        _editedDescription = State(initialValue: task.description)
        _editedDueDate = State(initialValue: task.dueDate)
        _editedPriority = State(initialValue: task.priority)
        _editedCategories = State(initialValue: task.categories)
    }
    
    var body: some View {
        NavigationView {
            Form {
                Section(header: Text("Task Details")) {
                    TextField("Title", text: $editedTitle)
                    TextEditor(text: $editedDescription)
                        .frame(height: 100)
                }
                
                Section(header: Text("Due Date")) {
                    DatePicker("Due Date", selection: $editedDueDate)
                }
                
                Section(header: Text("Priority")) {
                    Picker("Priority", selection: $editedPriority) {
                        Text("Low").tag(Task.TaskPriority.low)
                        Text("Medium").tag(Task.TaskPriority.medium)
                        Text("High").tag(Task.TaskPriority.high)
                    }
                    .pickerStyle(SegmentedPickerStyle())
                }
                
                Section(header: Text("Categories")) {
                    ForEach(editedCategories, id: \.self) { category in
                        Text(category)
                            .padding(.vertical, 4)
                    }
                    .onDelete(perform: deleteCategory)
                    
                    HStack {
                        TextField("New Category", text: $newCategory)
                        Button(action: addCategory) {
                            Image(systemName: "plus.circle.fill")
                        }
                        .disabled(newCategory.isEmpty)
                    }
                }
                
                if task.aiGenerated {
                    Section(header: Text("AI Generated")) {
                        Text("This task was generated by AI")
                            .foregroundColor(.gray)
                    }
                }
            }
            .navigationTitle("Task Details")
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Save") {
                        saveChanges()
                    }
                }
            }
        }
    }
    
    private func addCategory() {
        if !newCategory.isEmpty {
            editedCategories.append(newCategory)
            newCategory = ""
        }
    }
    
    private func deleteCategory(at offsets: IndexSet) {
        editedCategories.remove(atOffsets: offsets)
    }
    
    private func saveChanges() {
       /* $viewModel.updateTask*/(
            task,
            newTitle: editedTitle,
            newDescription: editedDescription,
            newDueDate: editedDueDate,
            newPriority: editedPriority,
            newCategories: editedCategories
        )
        dismiss()
    }
}

